package me.snwy.oasis

enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    COMMA, COLON, MINUS, PLUS, SLASH, STAR,
    LBRAC, RBRAC, LBRACE, RBRACE,

    // One or two character tokens.
    BANG, BANG_EQUAL, PIPE,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL, MOD,
    PLUS_EQUAL, MINUS_EQUAL, SLASH_EQUAL, STAR_EQUAL,
    RIGHT_PIPE, LEFT_PIPE, QUESTION, LAMBDA_ARROW,

    // Literals.
    IDENTIFIER, STRING, NUMBER, CHAR, BYTE,

    LET, PROTO, FN, FOR, IF, NIL, RETURN, TRUE, FALSE, WHILE, END,
    ELSE, AND, NOT, OR, NEW, IS, IMMUTABLE, TEST, ERROR, IN, BREAK, CONTINUE, OF,
    REL,

    EOF
}